### ISSUE TITLE
How Can I See Bird Scooter Prices?

### ISSUE THREAD

**Issue by amitayat** [jzarca01/node-bird#3]
Hi,

I'm trying to get the price for Bird scooter and can't see in the GetscooterDetalis parameter which represrent the price. I'm a contractor (Verified it also through the GetProfile) so I should see the prices.
please help.

Thanks,
Amitay

**Comment by jzarca01** [comment]
Hi Amitay,

I’m not a contractor so I didnt have access to this information when i developed this api.
If you want me to implement this feature, you would need to share your credentials with me so that i can look into it

**Comment by jzarca01** [comment]
**Closed for inactivity**
