### ISSUE TITLE
New Feature; give the option to set a custom timeout for axios 

### ISSUE THREAD

**Issue by salanza** [jzarca01/node-bird#4]
Hello All!

Last week, I noticed that bird services were taking a long time to respond. This long response time propagated to my micro service, since it was relying on node-bird to handle the timeout itself. I propose that we implement a function that will modify the axios config such that we can set our own timeout after instantiating the service. We will leave the default timeout as is (i.e. 0) so as to not break existing projects. 

What do you all think of my proposal? Any feedback will be greatly appreciated!

Regards

**Comment by jzarca01** [comment]
Hi Salman,

I checked your code, it would be more interested to use an interceptor that changes the default timeout if needed

Something like that
```
const EXTENDED_TIMEOUT = 6000000;

this.request.interceptors.response.use(
  config => config,
  (error) => {
    if (error.response.status === 408 || error.code === 'ECONNABORTED') {
      error.config.timeout = EXTENDED_TIMEOUT; 
      return this.request(error.config);
    }
    return Promise.reject(error);
  },
);
```

My library needs a refactoring the same way to handle access token and (soon) refresh token

**Comment by salanza** [comment]
Hello Jérémie!

Thanks for the response! Is there a reason you would prefer using an interceptor versus changing the config of the axios instance itself? My use case involved calling the same getScootersNearby route multiple times. Thus, I thought it would be more efficient to just set the timeout once versus utilizing an interceptor that would modify the call each time it is sent. 
 
Regards

**Comment by jzarca01** [comment]
I noticed a weird behaviour with axios where the instance would lose the dynamically added data after a few requests
This is why im gonna switch from setAccessToken to an interceptor

**Comment by jzarca01** [comment]
Here's something you could do
Fork the actual branch and and options to constructor

```
constructor(fdssfdsdf, sfdsfsd, options) {
this.request = axios.create({
dfsdfds
sdfdsfds
sdfdsfsdf
....options
})
```

**Comment by salanza** [comment]
Sounds like a plan!

**Comment by salanza** [comment]
Updated my forked branch. Constructor now has an optional param for timeout. If it is not specified, timeout will be set to 0 (i.e. no timeout) else it will utilize the timeout.

**Comment by jzarca01** [comment]
When you're ready, open a PR and i will review it
