### ISSUE TITLE
'node-bird@1.2.1' is not in the npm registry.

### ISSUE THREAD

**Issue by mebevilacqua** [jzarca01/node-bird#9]
Hey all, 

We wrote code that has dependency "node-bird": "^1.1.1" yet our builds are failing with:

'node-bird@1.1.1' is not in the npm registry.

Has this package been unpublished from npm?

Thanks!
Michael

**Comment by jzarca01** [comment]
Yes and the version is outdated too
It is available for purchase/licensing

**Comment by jzarca01** [comment]
A light version is also available for free : node-bird-lite
